const {
  REACT_APP_API_BASE_ROOT,
  REACT_APP_API_V1,
  REACT_APP_API_USERS_CTRLR_ROOT,
  REACT_APP_API_HOST,
  REACT_APP_API_ADMIN_CTRLR_ROOT
} = process.env;

module.exports = {
  API_HOST: REACT_APP_API_HOST,
  API_BASE_ROOT: REACT_APP_API_BASE_ROOT,
  API_V1: REACT_APP_API_V1,
  API_USERS_CTRLR_ROOT: REACT_APP_API_USERS_CTRLR_ROOT,
  API_ADMIN_CTRLR_ROOT: REACT_APP_API_ADMIN_CTRLR_ROOT
}